spring.application.name=movimentacao-service

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/movimentacao_db
spring.datasource.username=root
spring.datasource.password=Ca@050905

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true